#ifndef _SPARSE_ARRAY
#define _SPARSE_ARRAY
#include <bits/floatn-common.h>
#include <cstdlib>
#ifndef TYPE
#define TYPE float
#endif

typedef struct {
    int len;
    char x[];
} array;

typedef struct {
    // Number of samples in uncompressed array
    unsigned N;
    // Number of channels
    unsigned C;
    // Length of idx/mask/ptx arrays.
    unsigned samples;
    // Length of val
    unsigned size;
    TYPE *val;
    // array of the equivalent sparse index of the n-th element of val
    unsigned *idx;

    // array of masks indicating the occupancy of each channel of element val[ptx[i]]
    // Example: [ch0,ch2] -> 101, [ch1,ch2] -> 110
    unsigned char *mask;

    // [Optional] array of pointers (indexes from 0 to len-1) to the n-th
    // This array can be generated by accumulating the number of set bits per element of
    // the mask
    unsigned *ptx;

} Sparse_array;

void free_Sparse(Sparse_array *arr) {
    free(arr->val);
    free(arr->idx);
    free(arr->mask);
    free(arr->ptx);
    free(arr);
}

void cnz(unsigned &size, unsigned &samples, TYPE *arr, unsigned N, unsigned C) {
    size = 0;
    samples = 0;
    for (unsigned n = 0; n < N; n++) {
        bool occupied = false;
        for (unsigned c = 0; c < C; c++) {
            if (arr[n * C + c] != 0) {
                size++;
                occupied = true;
            }
        }
        samples = occupied ? samples + 1 : samples;
    }
}

Sparse_array *compress(TYPE *arr, unsigned N, unsigned C) {
    Sparse_array *sarr = (Sparse_array *)malloc(sizeof(Sparse_array));
    sarr->N = N;
    sarr->C = C;
    cnz(sarr->size, sarr->samples, arr, N, C);
    sarr->val = (TYPE *)malloc(sarr->size * sizeof(TYPE));
    sarr->idx = (unsigned *)malloc(sarr->samples * sizeof(unsigned));
    sarr->mask = (unsigned char *)malloc(sarr->samples * sizeof(unsigned char));
    unsigned j = 0;
    unsigned i = 0;
    for (unsigned n = 0; n < N; n++) {
        unsigned mask = 0;
        bool occupied = false;
        for (unsigned c = 0; c < C; c++) {
            if (arr[n * C + c] != 0) {
                occupied = true;
                sarr->val[j] = arr[n * C + c];
                j++;
                mask |= 1 << c;
            }
        }
        if (occupied) {
            sarr->idx[i] = n;
            sarr->mask[i] = mask;
            i++;
        }
    }
    return sarr;
}

void accumulate_indexes(Sparse_array *sarr) {
    sarr->ptx = (unsigned *)malloc(sizeof(unsigned) * sarr->samples);
    unsigned acc = 0;
    sarr->ptx[0] = 0;
    for (unsigned n = 0; n < sarr->samples - 1; n++) {
        acc += __builtin_popcount(sarr->mask[n]);
        sarr->ptx[n + 1] = acc;
    }
}

void decompress(TYPE *arr, unsigned &N, unsigned &C, Sparse_array *sarr) {
    N = sarr->N;
    C = sarr->C;
    unsigned ptx = 0;
    unsigned idx = 0;
    for (unsigned n = 0; n < sarr->N; n++) {
        for (unsigned c = 0; c < C; c++) {
            bool occupied = sarr->mask[idx] & 1 << c;
            unsigned offset = __builtin_popcount(
                ~(~0 << c) & sarr->mask[idx]); // find the position of channel c in val
            if (occupied && n == sarr->idx[idx]) {
                arr[n * C + c] = sarr->val[ptx + offset];
            } else {
                arr[n * C + c] = 0.0f;
            }
        }
        if (n == sarr->idx[idx]) {
            ptx += __builtin_popcount(sarr->mask[idx]);
            idx += 1;
        }
    }
}

#endif
